---
#
# Ansible managed
#
language: python

python:
  - "3.8"

services:
  - docker

env:
  global:
    namespace="robertdebock"
  matrix:
    - image="alpine" tag="latest"
    - image="alpine" tag="edge"
    - image="centos" tag="7"
    - image="centos" tag="latest"
    - image="debian" tag="latest"
    - image="debian" tag="bullseye"
    - image="fedora" tag="31"
    - image="fedora" tag="latest"
    - image="opensuse" tag="latest"
    - image="ubuntu" tag="latest"
    - image="ubuntu" tag="bionic"

cache:
  - pip

install:
  - pip install --upgrade pip
  - pip install tox

script:
  - function retry { counter=0 ; until "$@" ; do exit=$? ; counter=$(($counter + 1)) ; if [ $counter -ge 3 ] ; then return $exit ; fi ; done ; return 0; } ; retry tox --parallel all

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
  slack: "mAdTdI+AsKzVM8j6DIMdo3Cl0iNdez6lbOXPl0yd2tlY+BCdhRPrQEZCXWONUewdGyI8rY7Qqz88EMKfJCtWwAkwFmOcCtogexQToy7uirTFM8ThrhJGEDSrjavwcf2F7Eeulupv2blFatzBLE1cyf3q4B6kug7P8uNJuDES54b3fWKr2El1AVc1DtZA2brWV10yJL4iQJmhQZpIFXCKfkBxjeT8RsnlDsZ0LGeaTjCXfbE9W6Fe4Ccavy5QEPe38xdSwKXpO6/q/R7Jg9aBR0z6Qciztby9DEqWbf45DRNlZWzWjwboVCeBAHVPpnQDnN1DpJ7XKeCR5WsOcFE9R22y1iUKXAWE9TJC7D0jakAZ0ji4MSfhBVQGWX6obCb/F36fWMjpeXYioeT2ZmfX9gzxOrJ+TguV7NMRZgKSi0zo2tnZ79KsZcY8AqlsxVGi9VJx9YJPIRFWtUsu24bNV7W0JO39EaT8uvX7IzVk/bk9OsYGDPNLTxAazRgrKywm2r2eR04k6jpUMD1q0kwAFgaCKkkR5T+z1qpG1A6Yac66SxRxkmT1Y3yNpVhCauIzBRuIoSvLAxEIVdttxdeZaLh+pAyRDNiO3vNs7KvMH+LHYfdQiYyLjPWDexx90kypyyZ0SHm+HTmaMbJodPy5oYWVoir9nxZrjPFWau7aV9A="
  email: false
