---
# handlers file for auditd
- name: run augenrules
  command: augenrules
  notify: load rules

- name: load rules
  command: augenrules --load

- name: restart auditd
  service:
    name: "{{ auditd_service }}"
    state: restarted
    use: service
